# Generated by Django 2.1.2 on 2020-08-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_9',
            field=models.IntegerField(blank=True, choices=[(1, '水'), (2, 'お茶'), (3, 'ジュース')], null=True, verbose_name='サンプル項目9_選択肢（固定）'),
        ),
    ]
