# Generated by Django 2.1.2 on 2020-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200808_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sample_3',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sample_9',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
